server:
  port: 8090
spring:
  application:
    name: students
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgresql:5432/students
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false    # Best practice to disable
    flyway:
      baseline-on-migrate: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
  cloud:
    kubernetes:
      discovery:
        enabled: true
      config:
        enabled: true
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
chaos-engineering:
  wait: false
  duration: 120
  kill-service: false
  return-500: false
  return-400: false
  return-429: false
